# Generated by Django 5.1.2 on 2025-04-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='compressed_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
    ]
