# Generated by Django 5.1.2 on 2025-04-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_job_compressed_url_remove_job_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='compressed_url',
            field=models.EmailField(default='Email@email.com', max_length=254),
        ),
    ]
