# Generated by Django 5.1.2 on 2025-04-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_job_compressed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Done')], default='P', editable=False, max_length=20),
        ),
    ]
