# Generated by Django 5.1.2 on 2025-04-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='compressed_url',
            field=models.CharField(max_length=255),
        ),
    ]
