# Generated by Django 5.1.2 on 2025-04-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_job_compressed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='compressed_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
